name: Continuous Deployment for Frontend

on:
  push:
    branches:
      - main
      - fe-cd
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  IMAGE_REPO_NAME: frontend
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 777371055675
  ECR_REGISTRY: 777371055675.dkr.ecr.us-east-1.amazonaws.com
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Run tests
        run: cd frontend && npm test

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: $ECR_REGISTRY
          REPOSITORY: $IMAGE_REPO_NAME
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 -t $IMAGE_REPO_NAME:$IMAGE_TAG .
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG

      - name: Output the image name to a file
        run: echo $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG > image_name.txt

      - name: Upload image name file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: image_name
          path: image_name.txt

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download image name file
        uses: actions/download-artifact@v2
        with:
          name: image_name
          path: .

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Read the image name
        id: image_name
        run: echo "::set-output name=image_name::$(cat image_name.txt)"

      - name: Set kubernetes config
        run: aws eks update-kubeconfig --region us-east-1 --name cluster

      - name: Download & install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Deploy to Kubernetes
        run: |
          cd frontend/k8s
          kustomize edit set image frontend=${{ env.ECR_REGISTRY }}/${{ env.IMAGE_REPO_NAME }}:${{ github.sha }}
          kustomize build . | kubectl apply -f -
