name: ci-fullstack-workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install the dependencies.
      - run: cd frontend && npm ci
      # Run the tests.
      - run: cd frontend && npm test
      # Run the linter.
      - run: cd frontend && npm run lint
      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
